name: date

on: [push]

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - run: date

    windows:
        runs-on: windows-latest
        steps:          
            - run: date

    macos:
        runs-on: macos-latest
        steps:                
            - run: date
    
    ubuntu_20-04:
        needs: [ubuntu,windows,macos]
        runs-on: ubuntu-20.04
        steps:                
            - run: date